# Generated by Django 3.1.2 on 2020-10-31 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='category',
            new_name='source',
        ),
    ]
